apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quarkus-demo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-slallema-tenant/quarkus-demo/quarkus-demo@sha256:419fdda89b878cfcd6f37104ee7ce492d3c730447cff00a242e0149ffdc5eebb
        name: my-java-quarkus
        resources: {}
status: {}
