apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quarkus-demo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-slallema-tenant/quarkus-demo/quarkus-demo@sha256:2e04cdfc1d707ceea99871872a21162404b7b013c06adc4c5f2ddb1484206d7b
        name: my-java-quarkus
        resources: {}
status: {}
