apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quarkus-demo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-slallema-tenant/quarkus-demo/quarkus-demo@sha256:6d92f25b05280ff59422ed95873277d49605b1fc887d79b93700d195bb6a9d5d
        name: my-java-quarkus
        resources: {}
status: {}
