apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/part-of: quarkus-demo
  name: quarkus-demo
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quarkus-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quarkus-demo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-slallema-tenant/quarkus-demo/quarkus-demo@sha256:13245dd37266725c90c0201bab4db80c3026dbf1607b803a65de02a832ef1dea
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
